---
services:
  oscar:
    container_name: "oscar"
    build:
      context: "."
      dockerfile: "./Containerfile"
      args:
        GITHUB_TOKEN: "${GITHUB_TOKEN:-}"
        GO_VERSION: "${GO_VERSION:-}"
        GOPRIVATE: "${GOPRIVATE:-}"
        http_proxy: "${http_proxy:-}"
        https_proxy: "${https_proxy:-}"
        MISE_GITHUB_TOKEN: "${MISE_GITHUB_TOKEN:-}"
        MISE_VERSION: "${MISE_VERSION:-v2025.12.0}" # NOTE: set via 'make set-mise-version'
    image: "${IMAGE_URI:-}"
    pull_policy: "build"
    command:
      - "ci"
    environment:
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      MISE_GITHUB_TOKEN: "${MISE_GITHUB_TOKEN}"
      GOPRIVATE: "${GOPRIVATE}"
    volumes:
      - type: "bind"
        source: "${PWD}"
        target: "/home/oscar/app"
      - type: "bind"
        source: "${HOME}/.oscar"
        target: "/home/oscar/.oscar"
    user: "1000"
