[tools]
github-cli = "prefix:2"
go = "prefix:1"
markdownlint-cli2 = "prefix:0.18"
# required for markdownlint-cli2
node = "prefix:24"
ripgrep = "prefix:14"
shellcheck = "prefix:0.11"
shfmt = "prefix:3"
uv = "prefix:0.8"
yamlfmt = "prefix:0.17"
yamllint = "prefix:1"

# Go tools
"go:honnef.co/go/tools/cmd/staticcheck" = { version = "latest" }
"go:github.com/mgechev/revive" = { version = "prefix:1" }
"go:github.com/kisielk/errcheck" = { version = "prefix:1" }
"go:golang.org/x/tools/cmd/goimports" = { version = "latest" }
"go:golang.org/x/vuln/cmd/govulncheck" = { version = "prefix:1" }
