# This reusable workflow allows for checking out the most "correct" ref from the repo based on the
# condition that triggered the caller Workflow

name: "Conditional checkout"

on:
  workflow_call: {}

jobs:
  checkout:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout PR branch"
        if: "github.event_name == 'pull_request'"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5.0.0
        with:
          fetch-depth: 0
          ref: "${{ github.event.pull_request.head.ref }}"
      - name: "Checkout main branch"
        if: "github.ref == 'refs/heads/main'"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5.0.0
        with:
          fetch-depth: 0
