---
name: "main"

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "opened"
      - "reopened"
      - "synchronize"

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  MISE_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  MAIN_REF: "refs/heads/main"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
    steps:
      - name: "Checkout PR branch"
        if: "github.event_name == 'pull_request'"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5.0.0
        with:
          fetch-depth: 0
          ref: "${{ github.event.pull_request.head.ref }}"
      - name: "Checkout main branch"
        if: "github.ref == 'refs/heads/main'"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5.0.0
        with:
          fetch-depth: 0
      - name: "Install system packages"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make
      - name: "Set up mise"
        uses: "jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566" # v3.2.0
        with:
          version: "2025.9.10"
          install: true # runs `mise install`
          cache: true
      - name: "Run CI Tasks"
        run: "make ci"
  deliver:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - name: "Checkout PR branch"
        if: "github.event_name == 'pull_request'"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5.0.0
        with:
          fetch-depth: 0
          ref: "${{ github.event.pull_request.head.ref }}"
      - name: "Checkout main branch"
        if: "github.ref == 'refs/heads/main'"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5.0.0
        with:
          fetch-depth: 0
      - name: "Install system packages"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make
      - name: "Set up mise"
        uses: "jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566" # v3.2.0
        with:
          version: "2025.9.10"
          install: true # runs `mise install`
          cache: true
      - name: "Set up Docker"
        if: "github.ref == '${{ env.MAIN_REF }}'"
        uses: "docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435" # v3.11.1
      - name: "Run Delivery Tasks"
        if: "github.ref == '${{ env.MAIN_REF }}'"
        run: "make deliver"
