name: main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # release v5.0.0
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make
      - name: Set up mise
        uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # release v3.2.0
        with:
          version: "2025.8.1"
          install: true # runs `mise install`
          cache: true
      - name: Run CI
        run: make ci

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Log in to GHCR
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # # Generate any tags we want for the images (https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md)
      # - name: Extract metadata (tags, labels) for OCI image
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ghcr.io/opensourcecorp/oscar
      #     tags: |
      #       type=sha

      # # non-mainline
      # - name: Build and push non-mainline OCI image
      #   if: github.ref != 'refs/heads/main'
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: Containerfile
      #     push: true
      #     tags:
      #       - "latest"
      #       - "${VERSION}"

      # # mainline
      # - name: Build and push mainline OCI image
      #   if: github.ref == 'refs/heads/main'
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     file: Containerfile
      #     push: true
      #     tags: ghcr.io/opensourcecorp/oscar:latest
